app:
  name: recipesimplifierbase  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gastroadmin?useSSL=false
    username: gastrouser
    password: gastropw
    #platform: mysql
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5DBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true   
        id:
          new_generator_mappings: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

---



# ==============================================================
# = Spring Security / Queries for AuthenticationManagerBuilder  
# ==============================================================
  queries: 
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?

  jwt:
    header: Authorization
    expires_in: 300 # 5 minutes
    mobile_expires_in: 600 # 10 minutes
    secret: queenvictoria


# ==============================================================
# = DB config
## ==============================================================
#CREATE USER 'gastrouser'@'localhost' IDENTIFIED BY 'gastropw';
#GRANT ALL PRIVILEGES ON *.* TO 'gastrouser'@'localhost' WITH GRANT OPTION;
#CREATE USER 'gastrouser'@'%' IDENTIFIED BY 'gastropw';
#GRANT ALL PRIVILEGES ON *.* TO 'gastrouser'@'%' WITH GRANT OPTION;
#mysql -u gastrouser -p -e "create database gastroadmin"

  image-store-path:
    recipe-images: ./images/recipe
