app:
  name: recipesimplifierbase  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gastroadmin?useSSL=false
    username: gastrouser
    password: gastropw
    #platform: mysql
    initialize: true
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5DBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true   
        id:
          new_generator_mappings: false
---

    
    
# ==============================================================
# = Spring Security / Queries for AuthenticationManagerBuilder  
# ==============================================================
  queries: 
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?

  jwt:
    header: Authorization
    expires_in: 300 # 5 minutes
    mobile_expires_in: 600 # 10 minutes
    secret: queenvictoria
